# Generated by Django 5.2.17 on 2026-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='airtable_record_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
